[project]
name = "microstack-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openstacksdk>=4.4.0",
    "pytest>=8.3.5",
    "requests>=2.32.3",
]
